### ISSUE TITLE
Memory leak with AfterDelay

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-c#123]
Consider the simple program
```
target C;

reactor Source {
    output out:int
    timer t(0,10 msec)
    reaction(t) -> out {=
        lf_set(out,1);
    =}
}

reactor Sink {
    input in:int
    reaction(in) {==}
}

main reactor {
    a = new Source()
    b = new Sink()
    a.out->b.in after 10 msec
}
```

I am working with such a program on the zephyr-port and noticed that we run out of memory. When running it on Linux with valgrind I also get this suspicious output:
![image](https://user-images.githubusercontent.com/21197938/199573423-330aa0ae-61d1-4fbd-9419-e91a7d97b571.png)

Without the after-delay I get:
![image](https://user-images.githubusercontent.com/21197938/199573576-c3b0c1bf-a10d-493a-b5ac-e71c5f7d25c6.png)

I believe the memory leak is related to the fact that the AfterDelay reactor calls `lf_schedule_copy` on its action to create the delay. This will use `malloc` to dynamically allocate memory for the token, and for some reason it is not freed

**Comment by erlingrj** [comment]
If I understand correctly the `token` field of a port struct will be NULL if we are dealing with a primitive typed port

**Comment by edwardalee** [comment]
I believe that the function generateForwardBody in in CReactionGenerator should be freeing this memory. It currently reads like this:
```
    public static String generateForwardBody(String outputName, String targetType, String actionName, boolean isTokenType) {
        return isTokenType ?
                String.join("\n",
                    DISABLE_REACTION_INITIALIZATION_MARKER,
                    "self->_lf_"+outputName+".value = ("+targetType+")self->_lf__"+actionName+".token->value;",
                    "self->_lf_"+outputName+".token = (lf_token_t*)self->_lf__"+actionName+".token;",
                    "((lf_token_t*)self->_lf__"+actionName+".token)->ref_count++;",
                    "self->_lf_"+outputName+".is_present = true;"
                ) :
                "lf_set("+outputName+", "+actionName+"->value);";
    }
```
I believe it should read something like this:
```
    public static String generateForwardBody(String outputName, String targetType, String actionName, boolean isTokenType) {
        return isTokenType ?
                String.join("\n",
                    DISABLE_REACTION_INITIALIZATION_MARKER,
                    "self->_lf_"+outputName+".value = ("+targetType+")self->_lf__"+actionName+".token->value;",
                    "self->_lf_"+outputName+".token = (lf_token_t*)self->_lf__"+actionName+".token;",
                    "((lf_token_t*)self->_lf__"+actionName+".token)->ref_count++;",
                    "self->_lf_"+outputName+".is_present = true;"
                ) :
                String.join("\n",
                   "lf_set("+outputName+", "+actionName+"->value);",
                   "free("+actionName+"->value);"
                );
    }
```
`lf_set` is a macro that copies primitive type values into the output port's field that holds the value.

**Comment by edwardalee** [comment]
Unfortunately, my proposed solution looks more complicated because _lf_done_using is not visible. Unfortunately, I don't understand the new architecture well enough to see how to make it visible.
