### ISSUE TITLE
Return value of lf_critical_section_enter() and exit() are inconsistent

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#135]
In platform.h, these functions are defined:
```
extern int lf_critical_section_enter();
extern int lf_critical_section_exit();
```
However, reactor.c discards the return value:
```
void _lf_critical_section_enter() {
    lf_critical_section_enter();
}
void _lf_critical_section_exit() {
    lf_critical_section_exit();
}
```
Shouldn't _lf_critical_section_enter and exit return an int consistently?  And shouldn't the return value be checked?

**Comment by erlingrj** [comment]
I agree, I will address this.
