### ISSUE TITLE
lib/util.c is never compiled and has includes which are not present

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-c#139]
lib/util.c implements some deprecated API, but it is apparently never compiled and it causes problems in arduino support and lf-buckler. I think it could just be removed

**Comment by lhstrh** [comment]
Maybe have a look and see whether it is referenced anywhere in the examples-lingua-franca repo?

**Comment by erlingrj** [comment]
A quick search reveals that the `request_stop()` is being several places in `examples-lingua-franca`. I can easily make the changes there. The question is: Do we wanna keep deprecated APIs around for that long? I see two solutions:
1. Rename util.c to deprecated.c to avoid naming conflicts for Arduino and lf_buckler
2. Remove util.c and update `examples-lingua-franca` to use `lf_request_stop`.

Do you @edwardalee wanna weigh in?

**Comment by lhstrh** [comment]
I think option 2 looks more attractive but I'm fine with either.

**Comment by edwardalee** [comment]
I also think we should use option 2.  If and when I get back to the token work, my plan is to eliminate the deprecated APIs there too.  This will delete a large amount of code, which I consider a good thing.

**Comment by erlingrj** [comment]
This has been done, as far as I can see
