### ISSUE TITLE
Deadline misses are not traced

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-c#168]
I was looking at the reaction invokation lags and noticed that if there is a deadline that is missed, we do not trace it. How should a deadline miss be traced? A proposal in pseudo-code

```
tracepoint_reaction_start
tracepont_deadline_miss
reaction->deadline_func()
tracepoint_reaction_stop
```

I.e. we trace the deadline as a "normal" reaction invokation, but add a deadline-miss point?

**Comment by erlingrj** [comment]
After some more consideration, I think it would suffice with a new trace point called e.g.
`tracepoint_reaction_deadline_miss(reaction, worker)`

It would then store the the logical and physical time (and thus the lag). I am not sure whehter we need to trace the beginning and start of the deadline handler

**Comment by edwardalee** [comment]
Yes, I suggest that simpler is better. Just tracing the deadline miss seems sufficient to me. We can always add more tracepoints later when we need them, so let's not prematurely clutter the traces.
