### ISSUE TITLE
Splitting rti.c to lib_rti.c for reuse of rti.c functions.

### ISSUE THREAD

**Issue by Jakio815** [lf-lang/reactor-c#170]
I'm planning to make a `secure_rti` executable, using `rti.c`'s functions. But I see the current code is putting all functions in `rti.c`, which has a `main()`, so the functions in the code is not reusable. What do you think about splitting up the code to a different `lib_rti.c` with a header `lib_rti.h`, and rti.c does `#include "lib_rti.h"`? @lhstrh @hokeun

**Comment by lhstrh** [comment]
Yes, that is a good idea.

**Comment by edwardalee** [comment]
I suggest naming things rti_secure and rti_lib (I.e., use "rti" as a prefix not a suffix).

**Comment by Jakio815** [comment]
Thanks for the feedback @edwardalee. I fixed it. It's working on #172.
