### ISSUE TITLE
Renamed files done incorrectly

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#173]
I think the files rti.c and rti.h were renamed incorrectly, I think by @Jakio815 . This purged the edit history and is making it extremely difficult to merge main into the tracing-federates branch in which I am working.  Can we backtrack this and do it right?  The way to rename a file is using `git mv` not to delete the old and add the new.

**Comment by lhstrh** [comment]
Sure. I think the way to do this would be to fork off, undo the merge
commit, make the changes you want, and file a new PR.

**Comment by Jakio815** [comment]
It's my bad. I'll use the `git mv`. I'll do it as soon as possible.

**Comment by edwardalee** [comment]
I also leaned recently a good way to split a file into two files while preserving the history of each part, in case that is relevant:

https://devblogs.microsoft.com/oldnewthing/20190916-00/?p=102892

**Comment by edwardalee** [comment]
I think this has been dealt with.
