### ISSUE TITLE
Time issues on Zephyr platform

### ISSUE THREAD

**Issue by siljesu** [lf-lang/reactor-c#227]
I am testing clock synchronization error and message delay, and currently there are significantly worse results after commit 97141dd9be6f10b090c3e79c278ddd8ae38ff5c7. Clock synchronization drifts about 10 times faster and message delay also shows drift (even though it should be independent of the clock synchronization). @erlingrj Do you have any idea what is causing this?

**Comment by erlingrj** [comment]
Sounds like a bug, will look into this

**Comment by siljesu** [comment]
Ok, it seems it is actually this commit: c2024edb4e8433ce103ad93bdb58f9cda4f30d34. And specifically in the lf_clock_gettime() function. 
Old:
```
now_cycles = k_cycle_get_32();
*t = (SECOND(1)/CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC)*now_cycles;
```
New, much more drift:
```
res = counter_get_value(_lf_counter_dev, &now_cycles);
now_nsec = counter_ticks_to_us(_lf_counter_dev, now_cycles)*1000ULL;
*t = now_nsec + _lf_timer_last_epoch_nsec;
```

**Comment by lhstrh** [comment]
@erlingrj should we just revert the problematic change identified by @siljesu?

**Comment by erlingrj** [comment]
I will have to take a closer look at this later. Ideally, we should have a set of integration tests that run on real hardware that can verify the timing behaviour. It is quite difficult to verify that from inside an emulation.

**Comment by erlingrj** [comment]
OK. I have reproduced this on the nrf52. Currently when I run a timer with 1sec period, it toggles a GPIO pin every 994msec. So there might be some rounding error or something here.

**Comment by erlingrj** [comment]
Hm. The problem on the nrf52 was that the default clock source for the Timer peripherals was low quality and it just drifted by a lot. Actually the low resolution clock used by the Zephyr kernel had way less drift...
