### ISSUE TITLE
Namespace polluted by header-only implementations of platform APIs

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-c#237]
In the work with introducing environments in the C target I found it necessary for `lf_types.h` to include `platform.h`, this means that the functions defined in `platform.h` will be in scope for the user. This was something @petervdonovan avoided with this PR I believe: https://github.com/lf-lang/reactor-c/pull/189. 

The real problem isn't putting  `platform.h` in scope, but rather that several platform APIs, e.g. for Windows implement a lot of stuff in the header files, and thus needs to include a bunch of windows header files which can create naming conflicts. Does anyone know why header-only implementations were chosen? To me it seems a lot cleaner to provide the implementation in separate source files which then can include the windows headers and not expose those further.

**Comment by petervdonovan** [comment]
Yep, this is a problem. #189 probably represents all I have to say about `windows.h`. On the internet you can find other people who also vent about `windows.h`, for example in the comments [here](https://stackoverflow.com/questions/61921246/is-include-windows-h-bad-practice). There might be a way to mitigate the problem using
```c
#define WIN32_LEAN_AND_MEAN
```

but of course it isn't in our power to fix `windows.h`.

**Comment by erlingrj** [comment]
But is there any reason that `windows.h` must be included for any files except `lf_windows_support.c`?

**Comment by petervdonovan** [comment]
Oh, I understand your question now. I do not know of any particular reason for that. I think something like what you describe was considered  as an alternative solution in #189.
