### ISSUE TITLE
Reference count failure

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#24]
In master together with reactor-c/main, in test/C/src/DelayArrayWithAfter.lf, we get this message
```
WARNING: Token being freed that has already been freed
```
This indicates the reference counting is not working correctly with `after` delays.  At some point, it did work.  I don't now when this error crept in.  The tests `DelayStructWithAfter.lf` and `DelayStructWithAfterOverlapped.lf` also exhibit the same problem.

**Comment by lhstrh** [comment]
Is this still and issue, @edwardalee, or can we close this?

**Comment by edwardalee** [comment]
This seems to have been fixed.
