### ISSUE TITLE
Extensions to the threaded API, do we really need the C11 threads platform?

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/reactor-c#290]
Hi.

The need to configure the worker-affinity (e.g. pin LF worker to a specific core) and to set the priority of the workers and the scheduling strategy of the underlying thread library is getting apparent. Especially in the static scheduler work. It doesn't make sense to let the Linux kernel migrate our workers around from core to core, we have our own scheduler that distributes the work.

I am experimenting with adding some new functions to the threaded API currently I am thinking of:

```
int lf_thread_scheduler_init();
int lf_thread_set_cpu(lf_thread_t thread, int cpu_number);
int lf_thread_set_priority(lf_thread_t thread, int priority);
lf_thread_t lf_thread_self();
```

The first function is meant to configure the underlying threads scheduler. On Linux this could be using a real-time scheduler like SCHED_FIFO or SCHED_RR. 

Anyways, there is a straight forward way of implementing this with `pthread`, probably also with the windows API. However, C11 Threads does not have a rich enough API to configure these things. We could still use C11 for the thread synchronization and extend it with pthreads for the scheduling. But is this additional preprocessing complexity worth it? What is actually the benefit of using C11 Threads when we have pthreads support? Are there any platforms with C11 support and not pthread support?

**Comment by erlingrj** [comment]
Actually, I am not even sure if we can use C11 Threads together with pthread API for setting CPU affinity of those threads.

**Comment by lhstrh** [comment]
Wasn't the attraction that C11 Threads were supported on both Windows and *nix? Not that it should carry that much weight, however...

**Comment by erlingrj** [comment]
@edwardalee Any thoughts here?

**Comment by edwardalee** [comment]
I do not know whether there are situations where C11 would be the only option available, but the classic way of dealing with this problem is simply to define the extended functions as "suggestions."  The C11 implementation of the functions would be empty.  If you choose C11 for any reason, then you don't get these optimizations.

This won't work, however, if empty implementations will result in incorrect execution of LF.  If that is the case, then we should bury C11 support.

**Comment by erlingrj** [comment]
OK that makes sense. I propose:

1. Working on an optional addition to the threading API which enables setting LF worker affinity and setting underlying thread scheduler and worker priorities
2. Expose the decision to use C11 or pthreads to the user with pthreads as the default. 
3. If we try to set the LF worker affinity with the C11 platform, then either A) Warning, B) Error or C) Do nothing. We will have to think a little about that.

**Comment by lhstrh** [comment]
@erlingrj, I think your proposal sounds good!

**Comment by erlingrj** [comment]
Could we schedule a slot on a weekly LF meeting for a discussion on this. I would like to clarify a few different concepts and how they relate:

1. An LF Worker
2. An OS Thread
3. A CPU core

A valid question is: "Is it the task of the LF runtime to modify the CPU affinities, thread priorities and scheduler strategies?" This can also be done "outside", i.e. from just a shell on the Linux system. I am inclined towards getting this control from the LF runtime side. I think the main argument against it is that it widens the scope of LF and things that we must understand and take responsibility for. It is, in a sense, easier to say that the user has to handle all of these OS related things

**Comment by lhstrh** [comment]
OK, I've reserved time for this on Nov 15.

**Comment by lsk567** [comment]
It would be great if someone could post the discussion summary here. I will unfortunately not make it to the discussion due to travel, but would definitely like to stay on top of this issue. Thanks.

**Comment by lhstrh** [comment]
@erlingrj posted his slides in the `#debrief` channel on Zulip.
