### ISSUE TITLE
Check return value of lf_mutex_lock and lf_mutex_unlock

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#327]
@erlingrj introduced macros `LF_MUTEX_LOCK` and `LF_MUTEX_UNLOCK` that optionally check the return value of `lf_mutex_lock` and `lf_mutex_unlock`.  This is particularly important for embedded platforms, but it is incompletely applied.  Remaining instances of `lf_mutex_lock` and `lf_mutex_unlock` need to be replaced with `LF_MUTEX_LOCK` and `LF_MUTEX_UNLOCK`.

**Comment by erlingrj** [comment]
This appears to be completed, so closing this
