### ISSUE TITLE
Publish first version of `reactor-c`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/reactor-c#350]
I propose to tag whichever ref was used in the last `lingua-franca` release as `v0.6.0` and release it. Then, going forward, we can do subsequent releases completely independently. This is a 5 minute process, so it's quick and easy for me to do it, but I wanted to post this issue first in case there are any objections to this proposal.

**Comment by edwardalee** [comment]
Sounds good to me.  I'll use v0.6.1 then as the first version where fed protocol identifies the version?

**Comment by lhstrh** [comment]
Use whatever version we want to be the next release of `reactor-c`. I'd say `0.7.0` would be more appropriate because it's a new feature, not a bug fix.

**Comment by lhstrh** [comment]
Done. See https://github.com/lf-lang/reactor-c/releases/tag/v0.6.0
