### ISSUE TITLE
Testing of Modular Runtime Schedulers

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/reactor-c#39]
#16 introduced a more modular scheduling API for the C runtime and introduced three schedulers as a starting point.

To ensure that all the available runtime schedulers are correct, the full relevant C test suit is run for each scheduler. 
This currently triples the total time of the C tests on GitHub Actions, both in reactor-c and in lingua-franca repositories.

To mitigate this, as discussed with @lhstrh, we should only use the default scheduler to run tests in the `lingua-franca` repository and limit the testing of all schedulers to just the `reactor-c` repo. Moreover, as an enhancement, we could create multiple CI tasks for each scheduler on GitHub Actions to speed up the total time needed to run the tests.

**Comment by lhstrh** [comment]
Should we test all schedulers on all platforms, or only on Linux?

**Comment by Soroosh129** [comment]
I think it’s probably better to test on all platforms, since there are a lot of platform-specific functions that are really tempting to use for schedulers, like [sched_setaffinity(2)](http://linux.die.net/man/2/sched_setaffinity).

**Comment by lhstrh** [comment]
This is done. See: https://github.com/lf-lang/reactor-c/runs/5176052780?check_suite_focus=true
