### ISSUE TITLE
Enhanced tokens for more flexible memory management

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#44]
In our conversation with @rcakella today, it became clear that we need to enhance the token mechanism in the C infrastructure with a token that carries its own destructor. Specifically, you can currently use some of the SET functions, for example SET_NEW, to dynamically allocate memory for an outgoing message, and then a reference counting mechanism is used to later free this memory when it is no longer used. But this will not work if your message is, for example, a struct that contains pointers to dynamically allocated memory. Only the struct will be freed, not the pointed to memory. A simple solution, I think, would be to augment the token_t struct with a destructor, a function pointer. If this is NULL, then free() will be used, as now. If it is non-null, then the specified function will be invoked instead. We will then provide another variant of SET that takes the destructor as an argument.

**Comment by housengw** [comment]
passing the destructor to `SET_NEW` might be tricky in the remote federated case since the `token` at the input port of the receiving federate is allocated using a network control reaction under the hood (in `federate.c`). 

I think a cleaner solution might be to make the destructor part of the struct instead of the token.

**Comment by edwardalee** [comment]
I had not thought about using the token destructor across federates. In fact, I don't think it makes sense to use across federates. I think we should rely on the serialization/deserialization scheme to be able to work at the receiving end with the default destructor (which just calls free()).  The sending end could use the provided destructor after serializing the data.

**Comment by housengw** [comment]
closed by #66
