### ISSUE TITLE
Proposal for RTI docker image Continuous Deployment

### ISSUE THREAD

**Issue by Depetrol** [lf-lang/reactor-c#470]
Currently the docker [RTI image](https://hub.docker.com/r/lflang/rti/tags) in Docker hub is 6 months ago. This can cause unintended failures in the docker target with message type mismatches. I'm proposing we add a continuous deployment pipeline that:

- deploy the RTI in reactor-c commit in lingua-franca `master` branch as `lflang/rti:latest` 
- deploy versioned RTI images that matches lingua franca release versions as `lflang/rti:<version>`

**Comment by edwardalee** [comment]
Ok, but it’s only a temporary fix.  The next time the RTI is updated, the same issue will arise.

**Comment by lhstrh** [comment]
> Ok, but it’s only a temporary fix. The next time the RTI is updated, the same issue will arise.

No, the point is that the issue won't arise any longer (as long as you're using Docker) because each push to `master` will result in an updated image being pushed to DockerHub.

**Comment by lhstrh** [comment]
Automatically published images can be found here: https://hub.docker.com/r/lflang/rti/tags
