### ISSUE TITLE
Causality loops in Modal models.

### ISSUE THREAD

**Issue by Jakio815** [lf-lang/reactor-c#493]
Looks like the `lfc` gets a causality loop on inputs from other modes. Here is an example.

The reactor `tm`'s initial mode is `One`, and due to the startup trigger, it gives an output `out`.

This `tm.out` is connected to `B.in`, and the output `B.out` is connected to `tm.trigger`.

Logically, the reactor `tm` is still in mode `One`, so the reaction in mode B can actually not be triggered, and this wouldn't create a causality loop.

However, lfc shows this causality loop.

This problem seems to happen because in compile time it doesn't know if the mode is in `One` or `Two`.

Am I correct about this problem? If I am, is this intended? Or can this even be fixed?

```
target C
reactor two_modes {
    input trigger: bool
    output out : bool
    initial mode One {
      reaction(startup) -> out {=
      =}
    }
    mode Two {
      reaction(trigger) -> out {=

      =}
    }
}

reactor B {
    input in: bool
    output out: bool
    reaction(in) -> out {=
    =}
}

main reactor {
    tm = new two_modes()
    b = new B()
    tm.out -> b.in
    b.out -> tm.trigger
}
```
![caputre](https://github.com/user-attachments/assets/12236b79-6cf8-48a5-b3f4-ecaf27a5f6ab)

**Comment by lhstrh** [comment]
There is no reachability analysis done on the modes. It seems reasonable to assume that each mode is reachable; a mode that's unreachable is just dead code. Thus, assuming that all modes must be reachable, none of them should introduce zero-delay feedback. The compiler correctly flags this in your example. However, it looks like mode Two isn't actually reachable -- it's dead code -- so the fix would be to just remove mode Two, and your program would still be functionally equivalent.

**Comment by Jakio815** [comment]
Oh, this was just an example code, trying to reproduce an error from a different student in class.

I see your point, since there is no reachability analysis, the policy is to just ensure that there is no zero-delay feedback.

Makes sense. Thank you!
