### ISSUE TITLE
Dereferencing null pointer

### ISSUE THREAD

**Issue by housengw** [lf-lang/reactor-c#62]
In line 540 of `reactor_common.c`, there is a check for `null` token `if (token == NULL || ...)`

If this condition is true, however, line 542 would de-reference the `element_size` field of the `null` token to create a new token. 
https://github.com/lf-lang/reactor-c/blob/ab54ee59662c5ed20831e11b607df0a7b53ecd05/core/reactor_common.c#L540-L542

**Comment by edwardalee** [comment]
Thanks for pointing this out. This code is two years old, and for some reason an assert checking for a null ptr was commented out.  I've replaced this with an assert. Fix in PR #63.
