### ISSUE TITLE
How to distribute RTI

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#76]
Now that the RTI is not code generated, how should a user install it? Do they have clone the reactor-c repo and build it from source?  Is there some way would bundle it with the command-line tools, at least?  Is there any way to bundle it with Epoch?

**Comment by lhstrh** [comment]
A version of the RTI is shipped with Epoch in the jar, but I don't think this is the mechanism we're looking for.

I think the RTI should be in its own repo. We could make installing it as easy as running a Bash script that pulls in the source code and runs `make install`...

We should also establish versioning for it, so it can easily be checked whether what is installed is sufficient to run a particular LF program.

**Comment by petervdonovan** [comment]
We might want to think about the name of the executable as well. The RTI is the only executable that I can think of whose name uses capital letters, and I don't know how much risk there is of naming collisions (since the name is so short).

**Comment by lhstrh** [comment]
My sense is that `xronos` might be a good name. I looked, and even in [AUR](https://aur.archlinux.org/) there is no such package by that name in existence currently.

**Comment by Soroosh129** [comment]
I think RTI is a recognizable acronym that immediately conveys, abstractly, what this process is doing (although admittedly to a relatively small audience). `xronos` seems to be much more obfuscated. If we want to rename RTI, we should come up with a name that conveys, abstractly, what it does (e.g., fed-master or fed-coordinator).

**Comment by Soroosh129** [comment]
On the `xronos` name, my suggestion would be to name `core/federated` to `core/xronos` and have RTI as a component of that.

**Comment by lhstrh** [comment]
My concern is that RTI is an acronym for an [entire class of systems](https://en.wikipedia.org/wiki/Run-time_infrastructure_(simulation)), and for anyone other than HLA experts, RTI doesn't mean mean (or could [mean many different things](https://www.google.com/search?q=define%3A+rti&ei=sIGqYuHcEPKekPIPhrac2AE&ved=0ahUKEwjh9I_L47D4AhVyD0QIHQYbBxsQ4dUDCA0&uact=5&oq=define%3A+rti&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEJECMgUIABCABDIGCAAQHhAHMgYIABAeEAcyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBggAEB4QBzoHCAAQRxCwAzoHCAAQsAMQQzoKCAAQ5AIQsAMYAToMCC4QyAMQsAMQQxgCOgQIABBDOgcIABCABBAKOgsILhCABBDHARCvAToHCAAQsQMQDToKCAAQsQMQgwEQDToNCC4QsQMQxwEQ0QMQDToKCC4QsQMQ1AIQDToECAAQDUoECEEYAEoECEYYAVCbCFjpDWCpD2gBcAF4AIABhgGIAZQGkgEDNS4zmAEAoAEByAEQwAEB2gEGCAEQARgJ2gEGCAIQARgI&sclient=gws-wiz))

**Comment by Soroosh129** [comment]
> My concern is that RTI is an acronym for an [entire class of systems](https://en.wikipedia.org/wiki/Run-time_infrastructure_(simulation)), and for anyone other than HLA experts, RTI doesn't mean anything (or could [mean many different things](https://www.google.com/search?q=define%3A+rti&ei=sIGqYuHcEPKekPIPhrac2AE&ved=0ahUKEwjh9I_L47D4AhVyD0QIHQYbBxsQ4dUDCA0&uact=5&oq=define%3A+rti&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEJECMgUIABCABDIGCAAQHhAHMgYIABAeEAcyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBwgAELEDEAoyBggAEB4QBzoHCAAQRxCwAzoHCAAQsAMQQzoKCAAQ5AIQsAMYAToMCC4QyAMQsAMQQxgCOgQIABBDOgcIABCABBAKOgsILhCABBDHARCvAToHCAAQsQMQDToKCAAQsQMQgwEQDToNCC4QsQMQxwEQ0QMQDToKCC4QsQMQ1AIQDToECAAQDUoECEEYAEoECEYYAVCbCFjpDWCpD2gBcAF4AIABhgGIAZQGkgEDNS4zmAEAoAEByAEQwAEB2gEGCAEQARgJ2gEGCAIQARgI&sclient=gws-wiz))

I agree with you. My point was that we shouldn't rename it to something even less immediately recognizable. See my two suggestions above.

**Comment by petervdonovan** [comment]
> I think RTI is a recognizable acronym that immediately conveys, abstractly, what this process is doing

I also like the name RTI for this reason.

When I brought up this point, I was mostly just reacting to the unconventional capitalization of the executable. What I had in mind was just to call it `rti` or, if we were worried about the executable being confused with something else, maybe something like `lf-rti`. Something like this would be sufficient to address Marten's point above.

**Comment by Soroosh129** [comment]
I like `lf-rti` too.

**Comment by lhstrh** [comment]
IDK, usually applications uses some arbitrary name that is recognizable doesn't really describe what it does, which makes sense, because the pool of available names would run dry quickly. I'm not sure about `lf-rti` because we might want to come up with other middle ware implementations down the line. If we _really_ want to use the term `rti` then maybe `xronos-rti` could work?

**Comment by Soroosh129** [comment]
`xronos-rti` sounds good too. This suggest we can rename `core/federated` to `core/xronos` then, and have `xronos-rti` as a component of that.

**Comment by lhstrh** [comment]
My point is that it is more important for a name to be catchy and memorable than it is for it to be descriptive...

**Comment by Soroosh129** [comment]
Why would the RTI specifically need a catchy name though? The RTI is just a small piece of a big puzzle that enables federated execution. For example, decentralized coordination entirely bypasses the RTI except for startup and shutdown (which arguably don't need to be coordinated by the RTI, a "leader" federate can do that).

**Comment by lhstrh** [comment]
> `xronos-rti` sounds good too. This suggest we can rename `core/federated` to `core/xronos` then, and have `xronos-rti` as a component of that.

Sounds good. Is the package rename necessary though? I was more concerned with the name of the binary, which I believe is what Peter commented on.

**Comment by lhstrh** [comment]
> Why would the RTI specifically need a catchy name though?

IMO, because users interact with it on the command line and they need to remember what to type :-)

**Comment by Soroosh129** [comment]
>  Is the package rename necessary though? 

No I don't think it's necessary. To me, it makes the branding more coherent perhaps. I agree that the name of the binary is a more urgent matter. I like the name `xronos-rti`.
