### ISSUE TITLE
vector implementation does not match documentation

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/reactor-c#92]
The [vector_at](https://github.com/lf-lang/reactor-c/blob/e1e2bd3b16a3a450c266550ffe745170136fadf0/core/utils/vector.h#L70) function in [vector.h](https://github.com/lf-lang/reactor-c/blob/main/core/utils/vector.h) states "Return a pointer that is contained in the vector at 'idx'."  But this is not what the implementation returns.  The implementation returns a pointer to the pointer that is contained at idx.  Is there a reason for this extra level of indirection in the implementation?

**Comment by Soroosh129** [comment]
>  Is there a reason for this extra level of indirection in the implementation?

I can take the blame for this design. The reason for this level of indirection is that the vector works with `void*` elements (which can be `NULL` at `idx`). The idea is that if you want to set the value at `idx` using `vector_at`, you need a pointer to the `void*` element.

**Comment by Soroosh129** [comment]
An alternative design would be to have a `vector_get_at(vector_t* v, size_t idx);` and a `vector_set_at(vector_t* v, size_t idx, void* element);`.
